// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModelProtocolBuffer.proto

package edu.dhbw.andobjviewer.models;

public final class ModelProtocolBuffer {
  private ModelProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BufferModel extends
      com.google.protobuf.GeneratedMessage {
    // Use BufferModel.newBuilder() to construct.
    private BufferModel() {
      initFields();
    }
    private BufferModel(boolean noInit) {}
    
    private static final BufferModel defaultInstance;
    public static BufferModel getDefaultInstance() {
      return defaultInstance;
    }
    
    public BufferModel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internal_static_edu_dhbw_andobjviewer_models_BufferModel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internal_static_edu_dhbw_andobjviewer_models_BufferModel_fieldAccessorTable;
    }
    
    // repeated .edu.dhbw.andobjviewer.models.BufferGroup groups = 1;
    public static final int GROUPS_FIELD_NUMBER = 1;
    private java.util.List<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup> groups_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup> getGroupsList() {
      return groups_;
    }
    public int getGroupsCount() { return groups_.size(); }
    public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup getGroups(int index) {
      return groups_.get(index);
    }
    
    // repeated .edu.dhbw.andobjviewer.models.BufferMaterial materials = 2;
    public static final int MATERIALS_FIELD_NUMBER = 2;
    private java.util.List<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial> materials_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial> getMaterialsList() {
      return materials_;
    }
    public int getMaterialsCount() { return materials_.size(); }
    public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial getMaterials(int index) {
      return materials_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup element : getGroupsList()) {
        if (!element.isInitialized()) return false;
      }
      for (edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial element : getMaterialsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup element : getGroupsList()) {
        output.writeMessage(1, element);
      }
      for (edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial element : getMaterialsList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup element : getGroupsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial element : getMaterialsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel result;
      
      // Construct using edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel();
        return builder;
      }
      
      protected edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel.getDescriptor();
      }
      
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel getDefaultInstanceForType() {
        return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.groups_ != java.util.Collections.EMPTY_LIST) {
          result.groups_ =
            java.util.Collections.unmodifiableList(result.groups_);
        }
        if (result.materials_ != java.util.Collections.EMPTY_LIST) {
          result.materials_ =
            java.util.Collections.unmodifiableList(result.materials_);
        }
        edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel) {
          return mergeFrom((edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel other) {
        if (other == edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel.getDefaultInstance()) return this;
        if (!other.groups_.isEmpty()) {
          if (result.groups_.isEmpty()) {
            result.groups_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup>();
          }
          result.groups_.addAll(other.groups_);
        }
        if (!other.materials_.isEmpty()) {
          if (result.materials_.isEmpty()) {
            result.materials_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial>();
          }
          result.materials_.addAll(other.materials_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.Builder subBuilder = edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGroups(subBuilder.buildPartial());
              break;
            }
            case 18: {
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.Builder subBuilder = edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMaterials(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .edu.dhbw.andobjviewer.models.BufferGroup groups = 1;
      public java.util.List<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup> getGroupsList() {
        return java.util.Collections.unmodifiableList(result.groups_);
      }
      public int getGroupsCount() {
        return result.getGroupsCount();
      }
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup getGroups(int index) {
        return result.getGroups(index);
      }
      public Builder setGroups(int index, edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.groups_.set(index, value);
        return this;
      }
      public Builder setGroups(int index, edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.Builder builderForValue) {
        result.groups_.set(index, builderForValue.build());
        return this;
      }
      public Builder addGroups(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.groups_.isEmpty()) {
          result.groups_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup>();
        }
        result.groups_.add(value);
        return this;
      }
      public Builder addGroups(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.Builder builderForValue) {
        if (result.groups_.isEmpty()) {
          result.groups_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup>();
        }
        result.groups_.add(builderForValue.build());
        return this;
      }
      public Builder addAllGroups(
          java.lang.Iterable<? extends edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup> values) {
        if (result.groups_.isEmpty()) {
          result.groups_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup>();
        }
        super.addAll(values, result.groups_);
        return this;
      }
      public Builder clearGroups() {
        result.groups_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .edu.dhbw.andobjviewer.models.BufferMaterial materials = 2;
      public java.util.List<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial> getMaterialsList() {
        return java.util.Collections.unmodifiableList(result.materials_);
      }
      public int getMaterialsCount() {
        return result.getMaterialsCount();
      }
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial getMaterials(int index) {
        return result.getMaterials(index);
      }
      public Builder setMaterials(int index, edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.materials_.set(index, value);
        return this;
      }
      public Builder setMaterials(int index, edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.Builder builderForValue) {
        result.materials_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMaterials(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.materials_.isEmpty()) {
          result.materials_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial>();
        }
        result.materials_.add(value);
        return this;
      }
      public Builder addMaterials(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.Builder builderForValue) {
        if (result.materials_.isEmpty()) {
          result.materials_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial>();
        }
        result.materials_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMaterials(
          java.lang.Iterable<? extends edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial> values) {
        if (result.materials_.isEmpty()) {
          result.materials_ = new java.util.ArrayList<edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial>();
        }
        super.addAll(values, result.materials_);
        return this;
      }
      public Builder clearMaterials() {
        result.materials_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.andobjviewer.models.BufferModel)
    }
    
    static {
      defaultInstance = new BufferModel(true);
      edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.andobjviewer.models.BufferModel)
  }
  
  public static final class BufferGroup extends
      com.google.protobuf.GeneratedMessage {
    // Use BufferGroup.newBuilder() to construct.
    private BufferGroup() {
      initFields();
    }
    private BufferGroup(boolean noInit) {}
    
    private static final BufferGroup defaultInstance;
    public static BufferGroup getDefaultInstance() {
      return defaultInstance;
    }
    
    public BufferGroup getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internal_static_edu_dhbw_andobjviewer_models_BufferGroup_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internal_static_edu_dhbw_andobjviewer_models_BufferGroup_fieldAccessorTable;
    }
    
    // repeated float groupVertices = 1;
    public static final int GROUPVERTICES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> groupVertices_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getGroupVerticesList() {
      return groupVertices_;
    }
    public int getGroupVerticesCount() { return groupVertices_.size(); }
    public float getGroupVertices(int index) {
      return groupVertices_.get(index);
    }
    
    // repeated float groupNormals = 2;
    public static final int GROUPNORMALS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> groupNormals_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getGroupNormalsList() {
      return groupNormals_;
    }
    public int getGroupNormalsCount() { return groupNormals_.size(); }
    public float getGroupNormals(int index) {
      return groupNormals_.get(index);
    }
    
    // repeated float groupTexcoords = 3;
    public static final int GROUPTEXCOORDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Float> groupTexcoords_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getGroupTexcoordsList() {
      return groupTexcoords_;
    }
    public int getGroupTexcoordsCount() { return groupTexcoords_.size(); }
    public float getGroupTexcoords(int index) {
      return groupTexcoords_.get(index);
    }
    
    // required string materialName = 4;
    public static final int MATERIALNAME_FIELD_NUMBER = 4;
    private boolean hasMaterialName;
    private java.lang.String materialName_ = "";
    public boolean hasMaterialName() { return hasMaterialName; }
    public java.lang.String getMaterialName() { return materialName_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMaterialName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (float element : getGroupVerticesList()) {
        output.writeFloat(1, element);
      }
      for (float element : getGroupNormalsList()) {
        output.writeFloat(2, element);
      }
      for (float element : getGroupTexcoordsList()) {
        output.writeFloat(3, element);
      }
      if (hasMaterialName()) {
        output.writeString(4, getMaterialName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getGroupVerticesList().size();
        size += dataSize;
        size += 1 * getGroupVerticesList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getGroupNormalsList().size();
        size += dataSize;
        size += 1 * getGroupNormalsList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getGroupTexcoordsList().size();
        size += dataSize;
        size += 1 * getGroupTexcoordsList().size();
      }
      if (hasMaterialName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getMaterialName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup result;
      
      // Construct using edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup();
        return builder;
      }
      
      protected edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.getDescriptor();
      }
      
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup getDefaultInstanceForType() {
        return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.groupVertices_ != java.util.Collections.EMPTY_LIST) {
          result.groupVertices_ =
            java.util.Collections.unmodifiableList(result.groupVertices_);
        }
        if (result.groupNormals_ != java.util.Collections.EMPTY_LIST) {
          result.groupNormals_ =
            java.util.Collections.unmodifiableList(result.groupNormals_);
        }
        if (result.groupTexcoords_ != java.util.Collections.EMPTY_LIST) {
          result.groupTexcoords_ =
            java.util.Collections.unmodifiableList(result.groupTexcoords_);
        }
        edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup) {
          return mergeFrom((edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup other) {
        if (other == edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.getDefaultInstance()) return this;
        if (!other.groupVertices_.isEmpty()) {
          if (result.groupVertices_.isEmpty()) {
            result.groupVertices_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.groupVertices_.addAll(other.groupVertices_);
        }
        if (!other.groupNormals_.isEmpty()) {
          if (result.groupNormals_.isEmpty()) {
            result.groupNormals_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.groupNormals_.addAll(other.groupNormals_);
        }
        if (!other.groupTexcoords_.isEmpty()) {
          if (result.groupTexcoords_.isEmpty()) {
            result.groupTexcoords_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.groupTexcoords_.addAll(other.groupTexcoords_);
        }
        if (other.hasMaterialName()) {
          setMaterialName(other.getMaterialName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 13: {
              addGroupVertices(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addGroupVertices(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              addGroupNormals(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addGroupNormals(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 29: {
              addGroupTexcoords(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addGroupTexcoords(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              setMaterialName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated float groupVertices = 1;
      public java.util.List<java.lang.Float> getGroupVerticesList() {
        return java.util.Collections.unmodifiableList(result.groupVertices_);
      }
      public int getGroupVerticesCount() {
        return result.getGroupVerticesCount();
      }
      public float getGroupVertices(int index) {
        return result.getGroupVertices(index);
      }
      public Builder setGroupVertices(int index, float value) {
        result.groupVertices_.set(index, value);
        return this;
      }
      public Builder addGroupVertices(float value) {
        if (result.groupVertices_.isEmpty()) {
          result.groupVertices_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.groupVertices_.add(value);
        return this;
      }
      public Builder addAllGroupVertices(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.groupVertices_.isEmpty()) {
          result.groupVertices_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.groupVertices_);
        return this;
      }
      public Builder clearGroupVertices() {
        result.groupVertices_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated float groupNormals = 2;
      public java.util.List<java.lang.Float> getGroupNormalsList() {
        return java.util.Collections.unmodifiableList(result.groupNormals_);
      }
      public int getGroupNormalsCount() {
        return result.getGroupNormalsCount();
      }
      public float getGroupNormals(int index) {
        return result.getGroupNormals(index);
      }
      public Builder setGroupNormals(int index, float value) {
        result.groupNormals_.set(index, value);
        return this;
      }
      public Builder addGroupNormals(float value) {
        if (result.groupNormals_.isEmpty()) {
          result.groupNormals_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.groupNormals_.add(value);
        return this;
      }
      public Builder addAllGroupNormals(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.groupNormals_.isEmpty()) {
          result.groupNormals_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.groupNormals_);
        return this;
      }
      public Builder clearGroupNormals() {
        result.groupNormals_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated float groupTexcoords = 3;
      public java.util.List<java.lang.Float> getGroupTexcoordsList() {
        return java.util.Collections.unmodifiableList(result.groupTexcoords_);
      }
      public int getGroupTexcoordsCount() {
        return result.getGroupTexcoordsCount();
      }
      public float getGroupTexcoords(int index) {
        return result.getGroupTexcoords(index);
      }
      public Builder setGroupTexcoords(int index, float value) {
        result.groupTexcoords_.set(index, value);
        return this;
      }
      public Builder addGroupTexcoords(float value) {
        if (result.groupTexcoords_.isEmpty()) {
          result.groupTexcoords_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.groupTexcoords_.add(value);
        return this;
      }
      public Builder addAllGroupTexcoords(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.groupTexcoords_.isEmpty()) {
          result.groupTexcoords_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.groupTexcoords_);
        return this;
      }
      public Builder clearGroupTexcoords() {
        result.groupTexcoords_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string materialName = 4;
      public boolean hasMaterialName() {
        return result.hasMaterialName();
      }
      public java.lang.String getMaterialName() {
        return result.getMaterialName();
      }
      public Builder setMaterialName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMaterialName = true;
        result.materialName_ = value;
        return this;
      }
      public Builder clearMaterialName() {
        result.hasMaterialName = false;
        result.materialName_ = getDefaultInstance().getMaterialName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.andobjviewer.models.BufferGroup)
    }
    
    static {
      defaultInstance = new BufferGroup(true);
      edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.andobjviewer.models.BufferGroup)
  }
  
  public static final class BufferMaterial extends
      com.google.protobuf.GeneratedMessage {
    // Use BufferMaterial.newBuilder() to construct.
    private BufferMaterial() {
      initFields();
    }
    private BufferMaterial(boolean noInit) {}
    
    private static final BufferMaterial defaultInstance;
    public static BufferMaterial getDefaultInstance() {
      return defaultInstance;
    }
    
    public BufferMaterial getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated float ambientlightArr = 2;
    public static final int AMBIENTLIGHTARR_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> ambientlightArr_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getAmbientlightArrList() {
      return ambientlightArr_;
    }
    public int getAmbientlightArrCount() { return ambientlightArr_.size(); }
    public float getAmbientlightArr(int index) {
      return ambientlightArr_.get(index);
    }
    
    // repeated float diffuselightArr = 3;
    public static final int DIFFUSELIGHTARR_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Float> diffuselightArr_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getDiffuselightArrList() {
      return diffuselightArr_;
    }
    public int getDiffuselightArrCount() { return diffuselightArr_.size(); }
    public float getDiffuselightArr(int index) {
      return diffuselightArr_.get(index);
    }
    
    // repeated float specularlightArr = 4;
    public static final int SPECULARLIGHTARR_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Float> specularlightArr_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Float> getSpecularlightArrList() {
      return specularlightArr_;
    }
    public int getSpecularlightArrCount() { return specularlightArr_.size(); }
    public float getSpecularlightArr(int index) {
      return specularlightArr_.get(index);
    }
    
    // required float shininess = 5;
    public static final int SHININESS_FIELD_NUMBER = 5;
    private boolean hasShininess;
    private float shininess_ = 0F;
    public boolean hasShininess() { return hasShininess; }
    public float getShininess() { return shininess_; }
    
    // optional string bitmapFileName = 6;
    public static final int BITMAPFILENAME_FIELD_NUMBER = 6;
    private boolean hasBitmapFileName;
    private java.lang.String bitmapFileName_ = "";
    public boolean hasBitmapFileName() { return hasBitmapFileName; }
    public java.lang.String getBitmapFileName() { return bitmapFileName_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      if (!hasShininess) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      for (float element : getAmbientlightArrList()) {
        output.writeFloat(2, element);
      }
      for (float element : getDiffuselightArrList()) {
        output.writeFloat(3, element);
      }
      for (float element : getSpecularlightArrList()) {
        output.writeFloat(4, element);
      }
      if (hasShininess()) {
        output.writeFloat(5, getShininess());
      }
      if (hasBitmapFileName()) {
        output.writeString(6, getBitmapFileName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      {
        int dataSize = 0;
        dataSize = 4 * getAmbientlightArrList().size();
        size += dataSize;
        size += 1 * getAmbientlightArrList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getDiffuselightArrList().size();
        size += dataSize;
        size += 1 * getDiffuselightArrList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getSpecularlightArrList().size();
        size += dataSize;
        size += 1 * getSpecularlightArrList().size();
      }
      if (hasShininess()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, getShininess());
      }
      if (hasBitmapFileName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getBitmapFileName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial result;
      
      // Construct using edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial();
        return builder;
      }
      
      protected edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.getDescriptor();
      }
      
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial getDefaultInstanceForType() {
        return edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.ambientlightArr_ != java.util.Collections.EMPTY_LIST) {
          result.ambientlightArr_ =
            java.util.Collections.unmodifiableList(result.ambientlightArr_);
        }
        if (result.diffuselightArr_ != java.util.Collections.EMPTY_LIST) {
          result.diffuselightArr_ =
            java.util.Collections.unmodifiableList(result.diffuselightArr_);
        }
        if (result.specularlightArr_ != java.util.Collections.EMPTY_LIST) {
          result.specularlightArr_ =
            java.util.Collections.unmodifiableList(result.specularlightArr_);
        }
        edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial) {
          return mergeFrom((edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial other) {
        if (other == edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.ambientlightArr_.isEmpty()) {
          if (result.ambientlightArr_.isEmpty()) {
            result.ambientlightArr_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.ambientlightArr_.addAll(other.ambientlightArr_);
        }
        if (!other.diffuselightArr_.isEmpty()) {
          if (result.diffuselightArr_.isEmpty()) {
            result.diffuselightArr_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.diffuselightArr_.addAll(other.diffuselightArr_);
        }
        if (!other.specularlightArr_.isEmpty()) {
          if (result.specularlightArr_.isEmpty()) {
            result.specularlightArr_ = new java.util.ArrayList<java.lang.Float>();
          }
          result.specularlightArr_.addAll(other.specularlightArr_);
        }
        if (other.hasShininess()) {
          setShininess(other.getShininess());
        }
        if (other.hasBitmapFileName()) {
          setBitmapFileName(other.getBitmapFileName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 21: {
              addAmbientlightArr(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addAmbientlightArr(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 29: {
              addDiffuselightArr(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addDiffuselightArr(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 37: {
              addSpecularlightArr(input.readFloat());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addSpecularlightArr(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 45: {
              setShininess(input.readFloat());
              break;
            }
            case 50: {
              setBitmapFileName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated float ambientlightArr = 2;
      public java.util.List<java.lang.Float> getAmbientlightArrList() {
        return java.util.Collections.unmodifiableList(result.ambientlightArr_);
      }
      public int getAmbientlightArrCount() {
        return result.getAmbientlightArrCount();
      }
      public float getAmbientlightArr(int index) {
        return result.getAmbientlightArr(index);
      }
      public Builder setAmbientlightArr(int index, float value) {
        result.ambientlightArr_.set(index, value);
        return this;
      }
      public Builder addAmbientlightArr(float value) {
        if (result.ambientlightArr_.isEmpty()) {
          result.ambientlightArr_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.ambientlightArr_.add(value);
        return this;
      }
      public Builder addAllAmbientlightArr(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.ambientlightArr_.isEmpty()) {
          result.ambientlightArr_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.ambientlightArr_);
        return this;
      }
      public Builder clearAmbientlightArr() {
        result.ambientlightArr_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated float diffuselightArr = 3;
      public java.util.List<java.lang.Float> getDiffuselightArrList() {
        return java.util.Collections.unmodifiableList(result.diffuselightArr_);
      }
      public int getDiffuselightArrCount() {
        return result.getDiffuselightArrCount();
      }
      public float getDiffuselightArr(int index) {
        return result.getDiffuselightArr(index);
      }
      public Builder setDiffuselightArr(int index, float value) {
        result.diffuselightArr_.set(index, value);
        return this;
      }
      public Builder addDiffuselightArr(float value) {
        if (result.diffuselightArr_.isEmpty()) {
          result.diffuselightArr_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.diffuselightArr_.add(value);
        return this;
      }
      public Builder addAllDiffuselightArr(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.diffuselightArr_.isEmpty()) {
          result.diffuselightArr_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.diffuselightArr_);
        return this;
      }
      public Builder clearDiffuselightArr() {
        result.diffuselightArr_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated float specularlightArr = 4;
      public java.util.List<java.lang.Float> getSpecularlightArrList() {
        return java.util.Collections.unmodifiableList(result.specularlightArr_);
      }
      public int getSpecularlightArrCount() {
        return result.getSpecularlightArrCount();
      }
      public float getSpecularlightArr(int index) {
        return result.getSpecularlightArr(index);
      }
      public Builder setSpecularlightArr(int index, float value) {
        result.specularlightArr_.set(index, value);
        return this;
      }
      public Builder addSpecularlightArr(float value) {
        if (result.specularlightArr_.isEmpty()) {
          result.specularlightArr_ = new java.util.ArrayList<java.lang.Float>();
        }
        result.specularlightArr_.add(value);
        return this;
      }
      public Builder addAllSpecularlightArr(
          java.lang.Iterable<? extends java.lang.Float> values) {
        if (result.specularlightArr_.isEmpty()) {
          result.specularlightArr_ = new java.util.ArrayList<java.lang.Float>();
        }
        super.addAll(values, result.specularlightArr_);
        return this;
      }
      public Builder clearSpecularlightArr() {
        result.specularlightArr_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required float shininess = 5;
      public boolean hasShininess() {
        return result.hasShininess();
      }
      public float getShininess() {
        return result.getShininess();
      }
      public Builder setShininess(float value) {
        result.hasShininess = true;
        result.shininess_ = value;
        return this;
      }
      public Builder clearShininess() {
        result.hasShininess = false;
        result.shininess_ = 0F;
        return this;
      }
      
      // optional string bitmapFileName = 6;
      public boolean hasBitmapFileName() {
        return result.hasBitmapFileName();
      }
      public java.lang.String getBitmapFileName() {
        return result.getBitmapFileName();
      }
      public Builder setBitmapFileName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBitmapFileName = true;
        result.bitmapFileName_ = value;
        return this;
      }
      public Builder clearBitmapFileName() {
        result.hasBitmapFileName = false;
        result.bitmapFileName_ = getDefaultInstance().getBitmapFileName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.andobjviewer.models.BufferMaterial)
    }
    
    static {
      defaultInstance = new BufferMaterial(true);
      edu.dhbw.andobjviewer.models.ModelProtocolBuffer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.andobjviewer.models.BufferMaterial)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_andobjviewer_models_BufferModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_andobjviewer_models_BufferModel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_andobjviewer_models_BufferGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_andobjviewer_models_BufferGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ModelProtocolBuffer.proto\022\034edu.dhbw.an" +
      "dobjviewer.models\"\211\001\n\013BufferModel\0229\n\006gro" +
      "ups\030\001 \003(\0132).edu.dhbw.andobjviewer.models" +
      ".BufferGroup\022?\n\tmaterials\030\002 \003(\0132,.edu.dh" +
      "bw.andobjviewer.models.BufferMaterial\"h\n" +
      "\013BufferGroup\022\025\n\rgroupVertices\030\001 \003(\002\022\024\n\014g" +
      "roupNormals\030\002 \003(\002\022\026\n\016groupTexcoords\030\003 \003(" +
      "\002\022\024\n\014materialName\030\004 \002(\t\"\225\001\n\016BufferMateri" +
      "al\022\014\n\004name\030\001 \002(\t\022\027\n\017ambientlightArr\030\002 \003(" +
      "\002\022\027\n\017diffuselightArr\030\003 \003(\002\022\030\n\020specularli",
      "ghtArr\030\004 \003(\002\022\021\n\tshininess\030\005 \002(\002\022\026\n\016bitma" +
      "pFileName\030\006 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_andobjviewer_models_BufferModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_andobjviewer_models_BufferModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_andobjviewer_models_BufferModel_descriptor,
              new java.lang.String[] { "Groups", "Materials", },
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel.class,
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferModel.Builder.class);
          internal_static_edu_dhbw_andobjviewer_models_BufferGroup_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_andobjviewer_models_BufferGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_andobjviewer_models_BufferGroup_descriptor,
              new java.lang.String[] { "GroupVertices", "GroupNormals", "GroupTexcoords", "MaterialName", },
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.class,
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferGroup.Builder.class);
          internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_andobjviewer_models_BufferMaterial_descriptor,
              new java.lang.String[] { "Name", "AmbientlightArr", "DiffuselightArr", "SpecularlightArr", "Shininess", "BitmapFileName", },
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.class,
              edu.dhbw.andobjviewer.models.ModelProtocolBuffer.BufferMaterial.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
