/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_dhbw_andar_CameraPreviewHandler */

#ifndef _Included_edu_dhbw_andar_CameraPreviewHandler
#define _Included_edu_dhbw_andar_CameraPreviewHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_dhbw_andar_CameraPreviewHandler_MODE_RGB
#define edu_dhbw_andar_CameraPreviewHandler_MODE_RGB 0L
#undef edu_dhbw_andar_CameraPreviewHandler_MODE_GRAY
#define edu_dhbw_andar_CameraPreviewHandler_MODE_GRAY 1L
/*
 * Class:     edu_dhbw_andar_CameraPreviewHandler
 * Method:    yuv420sp2rgb
 * Signature: ([BIII[B)V
 */
JNIEXPORT void JNICALL Java_edu_dhbw_andar_CameraPreviewHandler_yuv420sp2rgb
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler */

#ifndef _Included_edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler
#define _Included_edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_MIN_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_MIN_PRIORITY 1L
#undef edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_NORM_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_NORM_PRIORITY 5L
#undef edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_MAX_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_MAX_PRIORITY 10L
#undef edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_MIN_TIME
#define edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_MIN_TIME 1500L
#undef edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_ENSURE_TIME
#define edu_dhbw_andar_CameraPreviewHandler_AutoFocusHandler_ENSURE_TIME 10000L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS */

#ifndef _Included_edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS
#define _Included_edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS_MIN_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS_MIN_PRIORITY 1L
#undef edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS_NORM_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS_NORM_PRIORITY 5L
#undef edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS_MAX_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_CameraConstFPS_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_dhbw_andar_CameraPreviewHandler_ConversionWorker */

#ifndef _Included_edu_dhbw_andar_CameraPreviewHandler_ConversionWorker
#define _Included_edu_dhbw_andar_CameraPreviewHandler_ConversionWorker
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_dhbw_andar_CameraPreviewHandler_ConversionWorker_MIN_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_ConversionWorker_MIN_PRIORITY 1L
#undef edu_dhbw_andar_CameraPreviewHandler_ConversionWorker_NORM_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_ConversionWorker_NORM_PRIORITY 5L
#undef edu_dhbw_andar_CameraPreviewHandler_ConversionWorker_MAX_PRIORITY
#define edu_dhbw_andar_CameraPreviewHandler_ConversionWorker_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
