/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_dhbw_andopenglcam_MarkerInfo */

#ifndef _Included_edu_dhbw_andopenglcam_MarkerInfo
#define _Included_edu_dhbw_andopenglcam_MarkerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_dhbw_andopenglcam_MarkerInfo
 * Method:    artoolkit_init
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_edu_dhbw_andopenglcam_MarkerInfo_artoolkit_1init
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     edu_dhbw_andopenglcam_MarkerInfo
 * Method:    artoolkit_detectmarkers
 * Signature: ([BLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_edu_dhbw_andopenglcam_MarkerInfo_artoolkit_1detectmarkers
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     edu_dhbw_andopenglcam_MarkerInfo
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_dhbw_andopenglcam_MarkerInfo_draw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
